services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: broker
    command: python broker.py

  servidor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servidor
    command: python servidor.py
    depends_on:
      - broker

  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cliente
    command: python cliente.py
    stdin_open: true
    tty: true
    depends_on:
      - broker
      - servidor